app:
  security:
    oauth:
      client1:
        id: client1
        password: password
      get_token_path: /api/auth/oauth/token,/api/auth/login

spring:
  application:
    name: gateway-service

zuul:
  routes:
    todos:
      path: /api/todos/**
      service-id: todo-service
      sensitive-headers:
    auth:
      path: /api/auth/**
      url: http://localhost:8082/
      sensitive-headers:


ribbon:
  # Timeout for all micro services
  ReadTimeout: 60000 # Used for debugging if I set a breakpoint and I am tracing I have one minute to press resume.
  eureka:
    enabled: true

# Timeout for auth micro service
auth:
  ribbon:
    ReadTimeout: 60000 # Used for debugging if I set a breakpoint and I am tracing I have one minute to press resume.

eureka:
  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: warn
    com.melardev: trace
    org.springframework.cloud.netflix.zuul: trace